install usb-storage /bin/false
blacklist usb-storage

install firewire-ohci /bin/false
blacklist firewire-ohci

install dccp /bin/false
blacklist dccp

install sctp /bin/false
blacklist sctp

install rds /bin/false
blacklist rds

install tipc /bin/false
blacklist tipc
