services:
  openbao:
    image: openbao/openbao:2.5.4
    container_name: openbao
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      BAO_LOCAL_CONFIG: |
        disable_mlock = true
    command: server -config=/etc/openbao/openbao.hcl
    volumes:
      - ./openbao.hcl:/etc/openbao/openbao.hcl:ro
      - /srv/admin/data/openbao:/openbao/file
    networks:
      - admin-net

networks:
  admin-net:
    external: true
