version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /storage
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
http:
  addr: :5000
  secret: registry-secret
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://{{ service_domains.harbor }}/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
redis:
  addr: harbor-redis:6379
  db: 1
