version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /storage
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
http:
  addr: :5000
  secret: registry-secret
auth:
  htpasswd:
    realm: harbor-registry-basic-realm
    path: /etc/registry/passwd
validation:
  disabled: true
compatibility:
  schema1:
    enabled: true
redis:
  addr: harbor-redis:6379
  db: 1
