{% set traefik_letsencrypt_enabled = traefik_letsencrypt_enabled | default((not (ci_mode | default(false))) and (not (traefik.local_tls_enabled | default(false))) and ((cloudflare.dns_api_token | default('') | length) > 0) and ((acme_email | default('') | length) > 0)) %}
entryPoints:
  metrics:
    address: ":8082"
  websecure:
    address: ":443"
    http:
      tls:
{% if traefik_letsencrypt_enabled %}
        certResolver: letsencrypt
{% endif %}
api:
  dashboard: true
metrics:
  prometheus:
    entryPoint: metrics
ping:
  entryPoint: "websecure"
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "admin-net"
    exposedByDefault: false
{% if traefik_letsencrypt_enabled %}
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{ acme_email | mandatory('acme_email is required for LetsEncrypt') }}"
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
{% endif %}
log:
  level: INFO
accessLog: {}
