entryPoints:
  web:
    address: ":80"
api:
  dashboard: true
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
log:
  level: INFO
accessLog: {}
