entryPoints:
  metrics:
    address: ":8082"
  websecure:
    address: ":443"
api:
  dashboard: true
metrics:
  prometheus:
    entryPoint: metrics
ping:
  entryPoint: "websecure"
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
  docker:
    endpoint: "tcp://traefik-socket-proxy:2375"
    network: "admin-edge"
    exposedByDefault: false
log:
  level: INFO
accessLog: {}
