entryPoints:
  metrics:
    address: ":8082"
  websecure:
    address: ":443"
{% if crowdsec.enabled | default(false) | bool %}
    http:
      middlewares:
        - crowdsec-bouncer@file
{% endif %}
  cloudflarewebsecure:
    address: ":8443"
    forwardedHeaders:
      trustedIPs:
        - "{{ ((cloudflare.origin_network | default({})).cloudflared_ip | default('172.31.255.3')) }}/32"
{% if crowdsec.enabled | default(false) | bool %}
    http:
      middlewares:
        - crowdsec-bouncer@file
{% endif %}
api:
  dashboard: true
metrics:
  prometheus:
    entryPoint: metrics
ping:
  entryPoint: "websecure"
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
{% if crowdsec.enabled | default(false) | bool %}
experimental:
  plugins:
    crowdsec-bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: "{{ crowdsec.traefik_bouncer.plugin_version | default('v1.4.5') }}"
{% endif %}
log:
  level: INFO
accessLog: {}
