#!/usr/bin/env bash
set -euo pipefail

# Set up the CI environment with required directory structures and mock data.
# This simulates the state that Ansible would normally create on a real node.

export CI=true

# Create /srv/admin directory structure
mkdir -p /srv/admin/stacks /srv/admin/env /srv/admin/data /srv/admin/backups/local

# Deploy compose stacks to the expected runtime location
cp -a stacks/traefik /srv/admin/stacks/traefik
cp -a stacks/keycloak /srv/admin/stacks/keycloak
cp -a stacks/openbao /srv/admin/stacks/openbao
cp -a stacks/harbor /srv/admin/stacks/harbor
cp -a stacks/cloudflared /srv/admin/stacks/cloudflared

# Create mock env files (normally generated by Ansible from SOPS secrets)
cat > /srv/admin/env/keycloak.env <<'EOF'
KEYCLOAK_DB_PASSWORD=ci-mock-password
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=ci-mock-admin-password
EOF
cat > /srv/admin/env/harbor.env <<'EOF'
HARBOR_ADMIN_PASSWORD=ci-mock-harbor-password
EOF
cat > /srv/admin/env/cloudflared.env <<'EOF'
CLOUDFLARE_TUNNEL_TOKEN=ci-mock-tunnel-token
EOF
chmod 0600 /srv/admin/env/*.env

# Create /etc/admin-node directory
mkdir -p /etc/admin-node

echo "[ci-setup] Environment prepared"
