---
- name: Install Arch packages
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
      - jq
      - curl
      - restic
      - rsync
      - sops
      - age
      - python
      - sudo
      - openssh
      - nftables
      - fail2ban
      - audit
      - lynis
    state: present
